#!/usr/bin/env python

import os
import re
import sys
import subprocess
import logging
import optparse

from shell_utils import ShellUtils
                    
def main():
  paths = os.listdir('/etc/qemu-server')
  REGEX_TEMPLATE = '^t_([^.]+)\.conf$'
  
  print "Available KVM templates:"
  print "------------------------"
  
  for path in paths:
    match = re.match(REGEX_TEMPLATE, path)
    if match:
      print match.group(1)
    
  
if __name__ == '__main__':
  try:
    ShellUtils.configure_logging()
    main()
    exit(0)
  except Exception, e:
    print e
    exit(1)